version: "3"

services:

  dev:
    image: 16nsk/devcontainers
    volumes:
      - projects:/projects
      - user:/home/developer
    command: sleep infinity
    ports:
      - "${APP_PORT:-8000}:8000"
      - "${TEST_VAR}":8443

volumes:
  projects:
  user:
