version: "3"

services:

  dev:
    image: 16nsk/devcontainers
    volumes:
      - projects:/projects
      - user:/home/developer
    command: sleep infinity
    ports:
      - "${APP_PORT:-7000}:7000"
      - "${TEST_VAR}:7443"

volumes:
  projects:
  user:
